# Generated by Django 6.0.1 on 2026-09-26 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_elisabeth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mouvement de caisse', 'verbose_name_plural': 'Mouvements de caisse'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['full_name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contrat', 'verbose_name_plural': 'Contrats'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterModelOptions(
            name='financialaccount',
            options={'ordering': ['name'], 'verbose_name': 'Compte financier', 'verbose_name_plural': 'Comptes financiers'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['name'], 'verbose_name': 'Salle', 'verbose_name_plural': 'Salles'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-event_date', 'start_time'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RESERVATION', 'Réservation'), ('PAIEMENT', 'Paiement'), ('DEPENSE', 'Dépense'), ('SYSTEME', 'Système')], default='SYSTEME', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
