# Generated by Django 6.0.1 on 2026-09-29 11:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_elisabeth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashmovement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterModelOptions(
            name='financialaccount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='financial_account',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='financialaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='method',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='reference',
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='application_elisabeth.expense'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='application_elisabeth.refund'),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('ENTREE', 'Entrée (Paiement)'), ('SORTIE', 'Sortie (Dépense / Remboursement)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='application_elisabeth.payment'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_elisabeth.reservation'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('EAU', 'Eau'), ('ELECTRICITE', 'Électricité'), ('SALAIRE', 'Salaire'), ('AUTRE', 'Autre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Caisse'), ('BANK', 'Banque'), ('MOBILE', 'Mobile Money')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, max_length=12),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='application_elisabeth.reservation'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
